# SPDX-License-Identifier: GPL-2.0-or-later

CMD_VIA_GET_PROTOCOL_VERSION = 0x01
CMD_VIA_GET_KEYBOARD_VALUE = 0x02
CMD_VIA_SET_KEYBOARD_VALUE = 0x03
CMD_VIA_GET_KEYCODE = 0x04
CMD_VIA_SET_KEYCODE = 0x05
# 0x07/0x08/0x09 are multiplexed by channel: 0=custom, 1=backlight, 2=rgblight
CMD_VIA_CUSTOM_SET_VALUE = 0x07
CMD_VIA_CUSTOM_GET_VALUE = 0x08
CMD_VIA_CUSTOM_SAVE = 0x09
# Aliases for lighting (same commands, different channel)
CMD_VIA_LIGHTING_SET_VALUE = CMD_VIA_CUSTOM_SET_VALUE
CMD_VIA_LIGHTING_GET_VALUE = CMD_VIA_CUSTOM_GET_VALUE
CMD_VIA_LIGHTING_SAVE = CMD_VIA_CUSTOM_SAVE
CMD_VIA_MACRO_GET_COUNT = 0x0C
CMD_VIA_MACRO_GET_BUFFER_SIZE = 0x0D
CMD_VIA_MACRO_GET_BUFFER = 0x0E
CMD_VIA_MACRO_SET_BUFFER = 0x0F
CMD_VIA_GET_LAYER_COUNT = 0x11
CMD_VIA_KEYMAP_GET_BUFFER = 0x12
CMD_VIA_KEYMAP_SET_BUFFER = 0x13
CMD_VIA_ENCODER_GET = 0x14
CMD_VIA_ENCODER_SET = 0x15
CMD_VIA_VIAL_PREFIX = 0xFE
VIA_LAYOUT_OPTIONS = 0x02
VIA_SWITCH_MATRIX_STATE = 0x03
QMK_BACKLIGHT_BRIGHTNESS = 0x09
QMK_BACKLIGHT_EFFECT = 0x0A
QMK_RGBLIGHT_BRIGHTNESS = 0x80
QMK_RGBLIGHT_EFFECT = 0x81
QMK_RGBLIGHT_EFFECT_SPEED = 0x82
QMK_RGBLIGHT_COLOR = 0x83
VIALRGB_GET_INFO = 0x40
VIALRGB_GET_MODE = 0x41
VIALRGB_GET_SUPPORTED = 0x42
VIALRGB_SET_MODE = 0x41
CMD_VIAL_GET_KEYBOARD_ID = 0x00
CMD_VIAL_GET_SIZE = 0x01
CMD_VIAL_GET_DEFINITION = 0x02
CMD_VIAL_GET_ENCODER = 0x03
CMD_VIAL_SET_ENCODER = 0x04
CMD_VIAL_GET_UNLOCK_STATUS = 0x05
CMD_VIAL_UNLOCK_START = 0x06
CMD_VIAL_UNLOCK_POLL = 0x07
CMD_VIAL_LOCK = 0x08
CMD_VIAL_QMK_SETTINGS_QUERY = 0x09
CMD_VIAL_QMK_SETTINGS_GET = 0x0A
CMD_VIAL_QMK_SETTINGS_SET = 0x0B
CMD_VIAL_QMK_SETTINGS_RESET = 0x0C

# how much of a macro/keymap buffer we can read/write per packet
BUFFER_FETCH_CHUNK = 28

# When did we get support for advanced macros (including delays in macros)
VIAL_PROTOCOL_ADVANCED_MACROS = 2
# Support for safe matrix tester (with unlock)
VIAL_PROTOCOL_MATRIX_TESTER = 3
# When did we get support for qmk settings
VIAL_PROTOCOL_QMK_SETTINGS = 4
# When did we get support for 2-byte macros
VIAL_PROTOCOL_EXT_MACROS = 5

# Svalboard settings now use VIA custom keyboard values
# Value IDs defined in protocol/svalboard.py (must match firmware)

# Viable protocol v2 (0xDF - Dynamic Features)
# Replaces 0xFE (Vial) for dynamic features
VIABLE_PREFIX = 0xDF

# Command IDs (v2)
VIABLE_GET_PROTOCOL_INFO = 0x00
VIABLE_TAP_DANCE_GET = 0x01
VIABLE_TAP_DANCE_SET = 0x02
VIABLE_COMBO_GET = 0x03
VIABLE_COMBO_SET = 0x04
VIABLE_KEY_OVERRIDE_GET = 0x05
VIABLE_KEY_OVERRIDE_SET = 0x06
VIABLE_ALT_REPEAT_KEY_GET = 0x07
VIABLE_ALT_REPEAT_KEY_SET = 0x08
VIABLE_ONESHOT_GET = 0x09
VIABLE_ONESHOT_SET = 0x0A
VIABLE_SAVE = 0x0B
VIABLE_RESET = 0x0C
VIABLE_DEFINITION_SIZE = 0x0D
VIABLE_DEFINITION_CHUNK = 0x0E
VIABLE_QMK_SETTINGS_QUERY = 0x10
VIABLE_QMK_SETTINGS_GET = 0x11
VIABLE_QMK_SETTINGS_SET = 0x12
VIABLE_QMK_SETTINGS_RESET = 0x13
VIABLE_ERROR = 0xFF

# Viable protocol version
VIABLE_PROTOCOL_VERSION = 1

# Feature capability flags (from protocol info response)
VIABLE_FLAG_CAPS_WORD = 0x01
VIABLE_FLAG_LAYER_LOCK = 0x02
VIABLE_FLAG_ONESHOT = 0x04

